# Generated by Django 4.1 on 2022-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_session',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
