# Generated by Django 4.1 on 2022-08-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_tracker', '0004_alter_practice_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_session',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
